version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:80" # Porta externa 8004 mapeada para o NGINX no container
    volumes:
      - ./src:/app/src # Monta o diretório src para facilitar desenvolvimento
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo # Define o fuso horário
    deploy:
      replicas: 5
      mode: replicated