version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"  # Porta exclusiva para desenvolvimento
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]  # Comando para rodar no dev