#version: '3.8'
#
#services:
#  react-app:
#    image: app-front-suporte:latest
#    ports:
#      - "8004:80"
#    volumes:
#      - ./src:/app/src
#    environment:
#      - NODE_ENV=production
#    deploy:
#      replicas: 5
#     mode: replicated

### antigo docker compose
version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:80" # Porta externa 3000 mapeada para o NGINX no container
    volumes:
      - ./src:/app/src # Monta o diretório src para facilitar desenvolvimento
    environment:
      - NODE_ENV=production
